version: "3.9"

services:
  mysql:
    image: mariadb:11
    container_name: iplab-mysql
    environment:
      MARIADB_DATABASE: iplab
      MARIADB_USER: iplab
      MARIADB_PASSWORD: iplabpass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: iplab-app
    depends_on:
      - mysql
    network_mode: host
    privileged: true
